=== khawja-ghouse/Document-Repository/JAVA_Training/XML_XSLT_XSD/com.xmlexcises/src/main/resources/eventframework.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://attunedlabs.com/internalevents/Dispatcher"
	elementFormDefault="qualified">

	<xs:element name="EventFramework">
		<!-- XSD validation rules go inside this xs:elemet tag -->
		<xs:complexType>
			<!-- Elements inside the sequence must fallow the specified order -->
			<xs:sequence>
				<xs:element name="DispatchChanels">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="DispatchChanel" minOccurs="1"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>l
										<xs:element name="ChanelImplementation">
											<xs:complexType>
												<xs:attribute name="fqcn" type="xs:string"></xs:attribute>
												<xs:attribute name="beanRefid" type="xs:string"></xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element name="ChanelConfiguration">
											<xs:complexType mixed="true">
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="id" type="xs:string" />
									<xs:attribute name="description" type="xs:string" />
									<xs:attribute name="isEnabled" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="SystemEvents" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="SystemEvent" minOccurs="1"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="CamelSystemEventBuilder"
											minOccurs="1">
											<xs:complexType>
												<xs:attribute name="fqcn" type="xs:string"></xs:attribute>
												<xs:attribute name="beanRefid" type="xs:string"></xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element name="EventDispatchers">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="EventDispatcher">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="DispatchChanelId"
																	maxOccurs="unbounded" minOccurs="0">
																	<xs:complexType mixed="true">
																	</xs:complexType>
																</xs:element>
																<xs:element name="EventTransformation"
																	maxOccurs="unbounded" minOccurs="0">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="CustomTransformer"
																				maxOccurs="unbounded" minOccurs="0">
																				<xs:complexType>
																					<xs:attribute name="fqcn" type="xs:string"></xs:attribute>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																		<xs:attribute name="Type" type="xs:string"></xs:attribute>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>

									</xs:sequence>
									<xs:attribute name="id" type="xs:string" />
									<xs:attribute name="description" type="xs:string" />
									<xs:attribute name="isEnabled" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="Events" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Event" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>

										<xs:element name="EventParams" minOccurs="0"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="EventParam" minOccurs="1"
														maxOccurs="unbounded" />
												</xs:sequence>
												<xs:attribute name="dataType" type="xs:string" />
												<xs:attribute name="validationRegEx" type="xs:string" />
												<xs:attribute name="name" type="xs:string" />
											</xs:complexType>
										</xs:element>

										<xs:element name="CamelEventProducer" minOccurs="0"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="CamelProducerConfig"
														minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="component" type="xs:string" />
															<xs:attribute name="feature" type="xs:string" />
															<xs:attribute name="raiseOn" type="xs:string" />
															<xs:attribute name="serviceName" type="xs:string" />
														</xs:complexType>
													</xs:element>
													<xs:element name="CamelEventBuilder" minOccurs="0"
														maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>

																<xs:element name="OGNLMapping" minOccurs="0"
																	maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="Source" minOccurs="0"
																				maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="EventMapping"
																							minOccurs="0" maxOccurs="unbounded">
																							<xs:complexType>
																								<xs:attribute name="destination"
																									type="xs:string" />
																								<xs:attribute name="source" type="xs:string" />
																							</xs:complexType>

																						</xs:element>
																					</xs:sequence>

																					<xs:attribute name="from" type="xs:string" />
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>

																<xs:element name="EventBuilder" minOccurs="0">
																	<xs:complexType>
																		<xs:attribute name="beanRefid" type="xs:string" />
																		<xs:attribute name="fqcn" type="xs:string" />
																	</xs:complexType>
																</xs:element>

															</xs:sequence>
															<xs:attribute name="type" type="xs:string" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>

										<xs:element name="EventDispatchers">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="EventDispatcher">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="DispatchChanelId"
																	maxOccurs="unbounded" minOccurs="0">
																	<xs:complexType mixed="true">
																	</xs:complexType>
																</xs:element>
																<xs:element name="EventTransformation"
																	maxOccurs="unbounded" minOccurs="0">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="XSLTName" minOccurs="0"
																				maxOccurs="unbounded" />
																			<xs:element name="CustomTransformer"
																				maxOccurs="unbounded" minOccurs="0">
																				<xs:complexType>
																					<xs:attribute name="fqcn" type="xs:string"></xs:attribute>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																		<xs:attribute name="Type" type="xs:string"></xs:attribute>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>

									</xs:sequence>
									<xs:attribute name="id" type="xs:string" />
									<xs:attribute name="isEnabled" type="xs:boolean" />
									<xs:attribute name="type" type="xs:string" />
									<xs:attribute name="description" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== khawja-ghouse/Document-Repository/JAVA_Training/XML_XSLT_XSD/com.xmlexcises/eventframework.xml
<?xml version="1.0" encoding="UTF-8"?>

<EventFramework xmlns:nadeem="http://www.example.org/eventframeworkn/nadeem"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="eventframework.xsd">
	<DispatchChanels>

		<DispatchChanel id="FILE_STORE" description="file store"
			isEnabled="true">
			<ChanelImplementation
				fqcn="com.attunedlabs.eventframework.dispatcher.chanel.FileStoreDispatchChanel"
				beanRefid="fileStoreDispatcher" />
			<ChanelConfiguration>
				{"filepath":"/home/ubuntu/LogDispatcher","filename":"LogDispatchChanel.txt"}
			</ChanelConfiguration>
		</DispatchChanel>

		<DispatchChanel id="EVT_FILE_STORE" description="event file store"
			isEnabled="false">
			<ChanelImplementation
				fqcn="com.attunedlabs.eventframework.dispatcher.chanel.FileStoreDispatchChanel"
				beanRefid="fileEventStoreDispatcher" />
			<ChanelConfiguration>
				{"filepath":"/home/ubuntu/LogDispatcher","filename":"EventDispatchChanel.txt"}
			</ChanelConfiguration>
		</DispatchChanel>

		<DispatchChanel id="REST_CLIENT" description="rest client"
			isEnabled="false">
			<ChanelImplementation
				fqcn="com.attunedlabs.eventframework.dispatcher.chanel.RestClientPostDispatchChanel"
				beanRefid="restClientDispatcher" />
			<ChanelConfiguration> {"restpath":"http://localhost:9080/baseroute"}
			</ChanelConfiguration>
		</DispatchChanel>

		<DispatchChanel id="PRINT_REST_CLIENT" description="print rest client"
			isEnabled="false">
			<ChanelImplementation
				fqcn="com.attunedlabs.eventframework.dispatcher.chanel.RestClientPostDispatchChanel"
				beanRefid="restClientDispatcher" />
			<ChanelConfiguration>
				{"restpath":"http://192.168.1.120:9090/printservice"}
			</ChanelConfiguration>
		</DispatchChanel>

	</DispatchChanels>

	<SystemEvents>

		<SystemEvent id="SERVICE_COMPLETION_FAILURE"
			description="Standard Event for failure of every service Type"
			isEnabled="true">
			<CamelSystemEventBuilder
				fqcn="com.attunedlabs.eventframework.camel.eventproducer.ServiceCompletionFailureEventBuilder"
				beanRefid="ServiceEventBuilder" />
			<EventDispatchers>
				<EventDispatcher>
					<nadeem:DispatchChanelId>FILE_STORE</nadeem:DispatchChanelId>
					<EventTransformation Type="CUSTOM">
						<CustomTransformer
							fqcn="com.attunedlabs.eventframework.dispatcher.transformer.CustomLeapEventTransformer" />
					</EventTransformation>
				</EventDispatcher>
			</EventDispatchers>
		</SystemEvent>

		<SystemEvent id="SERVICE_COMPLETION_SUCCESS"
			description="Standard Event for sucess of every service Type"
			isEnabled="false">
			<CamelSystemEventBuilder
				fqcn="com.attunedlabs.eventframework.camel.eventproducer.ServiceCompletionSuccessEventBuilder"
				beanRefid="ServiceEventBuilder" />
			<EventDispatchers>
				<EventDispatcher>
					<DispatchChanelId>FILE_STORE</DispatchChanelId>
					<EventTransformation Type="CUSTOM">
						<CustomTransformer
							fqcn="com.attunedlabs.eventframework.dispatcher.transformer.CustomLeapEventTransformer" />
					</EventTransformation>
				</EventDispatcher>
			</EventDispatchers>
		</SystemEvent>

	</SystemEvents>

	<Events>

		<Event id="POLINEITEM_UNLOADED" type="internal" description="polineitem unloaded"
			isEnabled="true">
			<EventParams>
				<EventParam name="productid" dataType="string"
					validationRegEx="" />
				<EventParam name="tenantid" dataType="string"
					validationRegEx="" />
				<EventParam name="servicetype" dataType="string"
					validationRegEx="" />
			</EventParams>
			<CamelEventProducer>
				<CamelProducerConfig serviceName="baseContext"
					feature="polineitem" component="com.attunedlabs.datasource.service.InsertService"
					raiseOn="success" />
				<CamelEventBuilder type="OGNL">
					<OGNLMapping>
						<Source from="CamelExchange">
							<EventMapping destination="eventParam['servicetype']"
								source="In.headers['servicetype']" />
							<EventMapping destination="eventParam['tenant']"
								source="In.headers['tenantid']" />
						</Source>
					</OGNLMapping>
				</CamelEventBuilder>
			</CamelEventProducer>
			<EventDispatchers>
				<EventDispatcher>
					<DispatchChanelId>FILE_STORE</DispatchChanelId>
					<EventTransformation Type="XML-XSLT">
						<XSLTName>eventxmlTransformation.xsl</XSLTName>
					</EventTransformation>
				</EventDispatcher>
			</EventDispatchers>
		</Event>

		<Event id="INVENTORY_UPDATED" type="internal" description="inventory updated"
			isEnabled="false">
			<EventParams>
				<EventParam name="policyid" dataType="string"
					validationRegEx="" />
				<EventParam name="data" dataType="string"
					validationRegEx="" />
				<EventParam name="servicetype" dataType="string"
					validationRegEx="" />
			</EventParams>
			<CamelEventProducer>
				<CamelProducerConfig serviceName="baseContext"
					feature="polineitem" component="com.attunedlabs.datasource.dao.UpdateInventory"
					raiseOn="success" />
				<CamelEventBuilder type="CUSTOM">
					<EventBuilder
						fqcn="com.attunedlabs.eventframework.camel.eventbuilder.InventoryUpdateEventBuilder"
						beanRefid="inventoryUpdateBuilder" />
				</CamelEventBuilder>
			</CamelEventProducer>
			<EventDispatchers>
				<EventDispatcher>
					<DispatchChanelId>EVT_FILE_STORE</DispatchChanelId>
					<EventTransformation Type="CUSTOM">
						<CustomTransformer
							fqcn="com.attunedlabs.eventframework.dispatcher.transformer.CustomLeapEventTransformer" />
					</EventTransformation>
				</EventDispatcher>
			</EventDispatchers>
		</Event>

		<Event id="POLINEITEM_PROCESSED" type="internal" description="polineitem processed"
			isEnabled="false">
			<EventParams>
				<EventParam name="eventid" dataType="string"
					validationRegEx="" />
				<EventParam name="tenantid" dataType="string"
					validationRegEx="" />
				<EventParam name="servicetype" dataType="string"
					validationRegEx="" />
			</EventParams>
			<CamelEventProducer>
				<CamelProducerConfig serviceName="baseContext"
					feature="polineitem" component="" raiseOn="success" />
				<CamelEventBuilder type='OGNL'>
					<OGNLMapping>
						<Source from="CamelExchange">
							<EventMapping destination="eventParam['servicetype']"
								source="In.headers['servicetype']" />
							<EventMapping destination="eventParam['tenant']"
								source="In.headers['tenantid']" />
						</Source>
					</OGNLMapping>
				</CamelEventBuilder>
			</CamelEventProducer>
			<EventDispatchers>
				<EventDispatcher>
					<DispatchChanelId>EVT_FILE_STORE</DispatchChanelId>
					<EventTransformation Type="JSON" />
				</EventDispatcher>
			</EventDispatchers>
		</Event>

		<Event id="POLINEITEM_PROC_FAILED" type="internal"
			description="polineitem process failed" isEnabled="false">
			<EventParams>
				<EventParam name="eventid" dataType="string"
					validationRegEx="" />
				<EventParam name="tenantid" dataType="string"
					validationRegEx="" />
				<EventParam name="servicetype" dataType="string"
					validationRegEx="" />
			</EventParams>
			<CamelEventProducer>
				<CamelProducerConfig serviceName="baseContext"
					feature="polineitem" component="" raiseOn="failure" />
				<CamelEventBuilder type='OGNL'>
					<OGNLMapping>
						<Source from="CamelExchange">
							<EventMapping destination="eventParam['servicetype']"
								source="In.headers['servicetype']" />
							<EventMapping destination="eventParam['tenant']"
								source="In.headers['tenantid']" />
						</Source>
					</OGNLMapping>
				</CamelEventBuilder>
			</CamelEventProducer>
			<EventDispatchers>
				<EventDispatcher>
					<DispatchChanelId>EVT_FILE_STORE</DispatchChanelId>
					<EventTransformation Type="CUSTOM">
						<CustomTransformer
							fqcn="com.attunedlabs.eventframework.dispatcher.transformer.GenericLeapEventJsonTransformer" />
					</EventTransformation>
				</EventDispatcher>
			</EventDispatchers>
		</Event>

		<Event id="PRINT_SERVICE" type="internal" description="print service"
			isEnabled="false">
			<EventParams>
				<EventParam name="eventid" dataType="string"
					validationRegEx="" />
				<EventParam name="tenantid" dataType="string"
					validationRegEx="" />
			</EventParams>
			<CamelEventProducer>
				<CamelProducerConfig serviceName="baseContext"
					feature="labelservice" component="com.attunedlabs.wms20.services.printlabel.PrintLabel"
					raiseOn="success" />
				<CamelEventBuilder type='OGNL'>
					<OGNLMapping>
						<Source from="CamelExchange">
							<EventMapping destination="eventParam['servicetype']"
								source="In.headers['servicetype']" />
							<EventMapping destination="eventParam['tenant']"
								source="In.headers['tenantid']" />
						</Source>
					</OGNLMapping>
				</CamelEventBuilder>
			</CamelEventProducer>
			<EventDispatchers>
				<EventDispatcher>
					<DispatchChanelId>EVT_FILE_STORE</DispatchChanelId>
					<EventTransformation Type="CUSTOM">
						<CustomTransformer
							fqcn="com.attunedlabs.eventframework.dispatcher.transformer.GenericLeapEventJsonTransformer" />
					</EventTransformation>
				</EventDispatcher>
			</EventDispatchers>
		</Event>

	</Events>
</EventFramework>
